from __future__ import annotations

from datetime import UTC, datetime
import json
import logging
from pathlib import Path
from typing import Any

import httpx
import yaml

from ..schemas import ProviderGatewaySyncResponse, RuntimeConfigApplyResponse, RuntimeConfigPreviewResponse


class LiteLLMSyncService:
    """Handle LiteLLM runtime config rendering and gateway model sync."""

    def __init__(self, store: Any) -> None:
        self.store = store

    def preview_litellm_runtime_config(self) -> RuntimeConfigPreviewResponse:
        config, _env_vars, provider_count, observability_backend = self.store._build_litellm_runtime_artifacts()
        model_count = len(config.get("model_list", []))
        return RuntimeConfigPreviewResponse(
            provider_count=provider_count,
            model_count=model_count,
            observability_backend=observability_backend,
            config=config,
        )

    def apply_litellm_runtime_config(self, output_dir: str | None = None) -> RuntimeConfigApplyResponse:
        config, env_vars, provider_count, observability_backend = self.store._build_litellm_runtime_artifacts()
        config_path, env_path = self.store._resolve_litellm_output_paths(output_dir)
        snapshot = self._capture_litellm_runtime_files(config_path, env_path)

        try:
            config_for_yaml = {k: v for k, v in config.items() if k != "model_list"}
            with config_path.open("w", encoding="utf-8") as config_file:
                yaml.safe_dump(config_for_yaml, config_file, default_flow_style=False, sort_keys=False)

            with env_path.open("w", encoding="utf-8") as env_file:
                env_file.write("# LiteLLM provider API keys - auto-generated by backend\n")
                env_file.write("# This file is generated by backend/app/store.py from control-plane state\n")
                for key, value in sorted(env_vars.items()):
                    env_file.write(f"{key}={value}\\n")

            response = RuntimeConfigApplyResponse(
                provider_count=provider_count,
                model_count=len(config.get("model_list", [])),
                observability_backend=observability_backend,
                config_path=str(config_path),
                env_path=str(env_path),
                written_at=datetime.now(UTC),
            )
            self._append_litellm_sync_audit(
                action="apply_config",
                status="success",
                detail="LiteLLM runtime files rendered",
                extra={
                    "provider_count": provider_count,
                    "model_count": len(config.get("model_list", [])),
                    "config_path": str(config_path),
                    "env_path": str(env_path),
                },
            )
            return response
        except Exception as exc:
            restored = self._restore_litellm_runtime_files(snapshot)
            self._append_litellm_sync_audit(
                action="apply_config",
                status="failed",
                detail=f"Failed to render runtime files: {exc}",
                extra={"rollback_restored": restored},
            )
            raise

    def sync_providers_to_litellm_config(self) -> None:
        config_path, env_path = self.store._resolve_litellm_output_paths(None)
        snapshot = self._capture_litellm_runtime_files(config_path, env_path)
        try:
            self.apply_litellm_runtime_config()
        except Exception as exc:
            logging.getLogger(__name__).error("Failed to sync providers to litellm config: %s", exc)
            return

        try:
            runtime_sync = self.sync_litellm_gateway_runtime()
            if not runtime_sync.ok:
                restored = self._restore_litellm_runtime_files(snapshot)
                self._append_litellm_sync_audit(
                    action="provider_auto_sync",
                    status="failed",
                    detail=runtime_sync.detail or "LiteLLM gateway sync failed",
                    extra={"rollback_restored": restored},
                )
                logging.getLogger(__name__).warning(
                    "LiteLLM gateway hot sync skipped/failed: %s",
                    runtime_sync.detail or "unknown error",
                )
            else:
                self._append_litellm_sync_audit(
                    action="provider_auto_sync",
                    status="success",
                    detail=runtime_sync.detail or "Provider auto sync finished",
                )
        except Exception as exc:
            restored = self._restore_litellm_runtime_files(snapshot)
            self._append_litellm_sync_audit(
                action="provider_auto_sync",
                status="failed",
                detail=f"Failed to hot sync LiteLLM gateway: {exc}",
                extra={"rollback_restored": restored},
            )
            logging.getLogger(__name__).warning("Failed to hot sync LiteLLM gateway: %s", exc)

    def sync_litellm_gateway_runtime(self) -> ProviderGatewaySyncResponse:  # noqa: C901
        config, env_vars, _provider_count, _observability_backend = self.store._build_litellm_runtime_artifacts()
        desired_models = self.store._build_litellm_hot_model_list(config.get("model_list", []), env_vars)
        synced_at = datetime.now(UTC)

        base_url = self.store._litellm_base_url()
        master_key = self.store._litellm_master_key()
        if not base_url or not master_key:
            response = ProviderGatewaySyncResponse(
                ok=False,
                model_count=len(desired_models),
                endpoint=None,
                detail="LiteLLM admin endpoint or master key is not configured",
                synced_at=synced_at,
            )
            self._append_litellm_sync_audit(
                action="gateway_model_sync",
                status="failed",
                detail=response.detail or "missing admin endpoint or key",
                extra={"model_count": len(desired_models)},
            )
            return response

        headers = {"Authorization": f"Bearer {master_key}", "Content-Type": "application/json"}
        timeout = httpx.Timeout(30.0, connect=5.0)
        errors: list[str] = []

        rollback_errors: list[str] = []
        deleted_backups: list[dict[str, Any]] = []
        added_success_names: set[str] = set()

        with httpx.Client(timeout=timeout) as client:
            try:
                resp = client.get(f"{base_url}/model/info", headers=headers)
                if resp.status_code >= 500:
                    current_models: dict[str, str] = {}
                else:
                    resp.raise_for_status()
                    current_models: dict[str, list[dict[str, Any]]] = {}
                    for model in resp.json().get("data", []):
                        if not isinstance(model, dict):
                            continue
                        model_name = model.get("model_name")
                        model_info = model.get("model_info")
                        if (
                            not isinstance(model_name, str)
                            or not model_name
                            or not isinstance(model_info, dict)
                            or not model_info.get("id")
                            or model_info.get("db_model") is not True
                        ):
                            continue
                        current_models.setdefault(model_name, []).append(
                            {
                                "id": str(model_info["id"]),
                                "litellm_params": model.get("litellm_params") or {},
                            }
                        )
            except Exception as exc:
                response = ProviderGatewaySyncResponse(
                    ok=False,
                    model_count=len(desired_models),
                    endpoint=f"{base_url}/model/info",
                    detail=f"Failed to fetch current gateway model list: {exc}",
                    synced_at=synced_at,
                )
                self._append_litellm_sync_audit(
                    action="gateway_model_sync",
                    status="failed",
                    detail=response.detail or "Failed to fetch current models",
                    extra={"model_count": len(desired_models)},
                )
                return response

            desired_by_name = {m["model_name"]: m for m in desired_models}
            desired_names = set(desired_by_name)
            current_names = set(current_models)
            to_delete: list[tuple[str, str]] = []
            to_add_names: set[str] = set(desired_names - current_names)

            def _canonical(value: dict[str, Any]) -> str:
                return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=True)

            def _collect_delete_ids(model_entries: list[dict[str, Any]]) -> list[str]:
                ids: list[str] = []
                seen: set[str] = set()
                for model_entry in model_entries:
                    candidate = str(model_entry.get("id", "")).strip()
                    if not candidate or candidate in seen:
                        continue
                    seen.add(candidate)
                    ids.append(candidate)
                return ids

            for model_name, model_entries in current_models.items():
                if model_name not in desired_names:
                    for delete_id in _collect_delete_ids(model_entries):
                        to_delete.append((model_name, delete_id))
                    continue

                desired_params = desired_by_name[model_name].get("litellm_params") or {}
                current_params = (model_entries[0].get("litellm_params") or {}) if model_entries else {}

                if _canonical(current_params) != _canonical(desired_params):
                    for delete_id in _collect_delete_ids(model_entries):
                        to_delete.append((model_name, delete_id))
                    to_add_names.add(model_name)
                    continue

            for model_name, model_id in sorted(to_delete):
                backup_payload = None
                for model_entry in current_models.get(model_name, []):
                    if str(model_entry.get("id", "")).strip() == model_id:
                        backup_payload = {
                            "model_name": model_name,
                            "litellm_params": model_entry.get("litellm_params") or {},
                        }
                        break
                try:
                    resp = client.post(
                        f"{base_url}/model/delete",
                        headers=headers,
                        json={"id": model_id},
                    )
                    if resp.status_code in {400, 404}:
                        detail = resp.text.lower()
                        if "not found" in detail or "does not exist" in detail:
                            continue
                    resp.raise_for_status()
                    if backup_payload:
                        deleted_backups.append(backup_payload)
                except Exception as exc:
                    errors.append(f"delete {model_name!r}: {exc}")

            for model_name in sorted(to_add_names):
                model = desired_by_name[model_name]
                payload: dict[str, Any] = {
                    "model_name": model["model_name"],
                    "litellm_params": model["litellm_params"],
                }
                if model.get("model_info"):
                    payload["model_info"] = model["model_info"]
                try:
                    resp = client.post(f"{base_url}/model/new", headers=headers, json=payload)
                    if resp.status_code in {400, 409}:
                        detail = resp.text.lower()
                        if "already" in detail or "exists" in detail or "duplicate" in detail:
                            continue
                    resp.raise_for_status()
                    added_success_names.add(model_name)
                except Exception as exc:
                    errors.append(f"add {model_name!r}: {exc}")

            if errors and (added_success_names or deleted_backups):
                try:
                    info_resp = client.get(f"{base_url}/model/info", headers=headers)
                    info_resp.raise_for_status()
                    current_rows = info_resp.json().get("data", [])
                    rollback_delete_ids: list[str] = []
                    for row in current_rows:
                        if not isinstance(row, dict):
                            continue
                        model_name = row.get("model_name")
                        model_info = row.get("model_info")
                        if (
                            isinstance(model_name, str)
                            and model_name in added_success_names
                            and isinstance(model_info, dict)
                            and model_info.get("db_model") is True
                            and model_info.get("id")
                        ):
                            rollback_delete_ids.append(str(model_info["id"]))

                    for delete_id in rollback_delete_ids:
                        try:
                            client.post(f"{base_url}/model/delete", headers=headers, json={"id": delete_id}).raise_for_status()
                        except Exception as exc:
                            rollback_errors.append(f"rollback delete id={delete_id}: {exc}")

                    for item in deleted_backups:
                        try:
                            client.post(
                                f"{base_url}/model/new",
                                headers=headers,
                                json={
                                    "model_name": item["model_name"],
                                    "litellm_params": item.get("litellm_params") or {},
                                },
                            ).raise_for_status()
                        except Exception as exc:
                            rollback_errors.append(f"rollback re-add {item.get('model_name')!r}: {exc}")
                except Exception as exc:
                    rollback_errors.append(f"rollback bootstrap failed: {exc}")

        removed_model_names = {model_name for model_name, _ in to_delete}
        detail = (
            f"Gateway synced: +{len(to_add_names)} added, "
            f"-{len(removed_model_names)} model(s) removed ({len(to_delete)} row(s)), "
            f"{len(desired_names)} total"
        )
        if errors:
            detail += f"; {len(errors)} error(s): {'; '.join(errors[:3])}"
        if len(errors) > 3:
            detail += f" (and {len(errors) - 3} more)"
        if rollback_errors:
            detail += f"; rollback errors: {'; '.join(rollback_errors[:2])}"
            if len(rollback_errors) > 2:
                detail += f" (and {len(rollback_errors) - 2} more)"
        response = ProviderGatewaySyncResponse(
            ok=not errors,
            model_count=len(desired_names),
            endpoint=f"{base_url}/model/new",
            detail=detail,
            synced_at=synced_at,
        )
        self._append_litellm_sync_audit(
            action="gateway_model_sync",
            status="success" if response.ok else "failed",
            detail=response.detail or "Gateway model sync finished",
            extra={
                "desired_model_count": len(desired_names),
                "deleted_rows": len(to_delete),
                "added_models": len(to_add_names),
                "errors": len(errors),
                "rollback_errors": len(rollback_errors),
            },
        )
        return response

    @staticmethod
    def _capture_litellm_runtime_files(config_path: Path, env_path: Path) -> dict[str, dict[str, Any]]:
        def _capture(path: Path) -> dict[str, Any]:
            if not path.exists():
                return {"exists": False, "content": ""}
            return {"exists": True, "content": path.read_text(encoding="utf-8")}

        return {
            "config": _capture(config_path),
            "env": _capture(env_path),
            "config_path": str(config_path),
            "env_path": str(env_path),
        }

    @staticmethod
    def _restore_litellm_runtime_files(snapshot: dict[str, Any]) -> bool:
        try:
            config_path = Path(str(snapshot.get("config_path", "")))
            env_path = Path(str(snapshot.get("env_path", "")))
            for key, path in (("config", config_path), ("env", env_path)):
                info = snapshot.get(key, {}) if isinstance(snapshot, dict) else {}
                existed = bool(info.get("exists")) if isinstance(info, dict) else False
                content = str(info.get("content", "")) if isinstance(info, dict) else ""

                if existed:
                    path.parent.mkdir(parents=True, exist_ok=True)
                    path.write_text(content, encoding="utf-8")
                elif path.exists():
                    path.unlink()
            return True
        except Exception:
            return False

    def _append_litellm_sync_audit(
        self,
        *,
        action: str,
        status: str,
        detail: str,
        extra: dict[str, Any] | None = None,
    ) -> None:
        try:
            config_path, _ = self.store._resolve_litellm_output_paths(None)
            litellm_dir = config_path.parent
            litellm_dir.mkdir(parents=True, exist_ok=True)
            audit_path = litellm_dir / "runtime_sync_audit.jsonl"
            event = {
                "at": datetime.now(UTC).isoformat(),
                "action": action,
                "status": status,
                "detail": detail,
                "extra": extra or {},
            }
            with audit_path.open("a", encoding="utf-8") as file_obj:
                file_obj.write(json.dumps(event, ensure_ascii=False) + "\\n")
        except Exception:
            logging.getLogger(__name__).warning("Failed to append LiteLLM sync audit log")
