from __future__ import annotations

from .schemas import ProviderPresetRecord

PRESET_PROVIDERS: list[ProviderPresetRecord] = [
    ProviderPresetRecord(
        key="openai_official",
        name="OpenAI Official",
        provider_type="openai",
        default_base_url="https://api.openai.com",
        api_format="openai",
        suggested_apps=["codex", "open_webui", "opencode", "openclaw"],
    ),
    ProviderPresetRecord(
        key="anthropic_official",
        name="Anthropic Official",
        provider_type="anthropic",
        default_base_url="https://api.anthropic.com",
        api_format="anthropic",
        suggested_apps=["claude"],
    ),
    ProviderPresetRecord(
        key="google_gemini",
        name="Google Gemini Official",
        provider_type="gemini",
        default_base_url="https://generativelanguage.googleapis.com",
        api_format="openai",
        suggested_apps=["gemini", "open_webui"],
    ),
    ProviderPresetRecord(
        key="azure_openai",
        name="Azure OpenAI",
        provider_type="azure_openai",
        default_base_url="https://example.openai.azure.com",
        api_format="openai",
        suggested_apps=["codex", "open_webui", "opencode", "openclaw"],
    ),
    ProviderPresetRecord(
        key="deepseek",
        name="DeepSeek",
        provider_type="deepseek",
        default_base_url="https://api.deepseek.com",
        api_format="openai",
        suggested_apps=["claude", "opencode", "openclaw", "open_webui"],
    ),
    ProviderPresetRecord(
        key="zhipu_glm",
        name="Zhipu GLM",
        provider_type="zhipu",
        default_base_url="https://open.bigmodel.cn/api/paas/v4",
        api_format="openai",
        suggested_apps=["claude", "opencode", "openclaw", "open_webui"],
    ),
    ProviderPresetRecord(
        key="zhipu_glm_en",
        name="Zhipu GLM (EN)",
        provider_type="zhipu",
        default_base_url="https://open.bigmodel.cn/api/paas/v4",
        api_format="openai",
        suggested_apps=["claude", "opencode", "openclaw", "open_webui"],
    ),
    ProviderPresetRecord(
        key="qwen_bailian",
        name="Bailian (Qwen)",
        provider_type="qwen",
        default_base_url="https://dashscope.aliyuncs.com/compatible-mode/v1",
        api_format="openai",
        suggested_apps=["claude", "opencode", "openclaw", "open_webui"],
    ),
    ProviderPresetRecord(
        key="qwen_coder",
        name="Qwen Coder",
        provider_type="qwen",
        default_base_url="https://dashscope.aliyuncs.com/compatible-mode/v1",
        api_format="openai",
        suggested_apps=["openclaw", "opencode", "codex", "open_webui"],
    ),
    ProviderPresetRecord(
        key="kimi",
        name="Kimi",
        provider_type="moonshot",
        default_base_url="https://api.moonshot.cn/v1",
        api_format="openai",
        suggested_apps=["claude", "opencode", "openclaw", "open_webui"],
    ),
    ProviderPresetRecord(
        key="kimi_for_coding",
        name="Kimi For Coding",
        provider_type="moonshot",
        default_base_url="https://api.moonshot.cn/v1",
        api_format="openai",
        suggested_apps=["claude", "codex", "opencode", "openclaw", "open_webui"],
    ),
    ProviderPresetRecord(
        key="stepfun",
        name="StepFun",
        provider_type="stepfun",
        default_base_url="https://api.stepfun.com/v1",
        api_format="openai",
        suggested_apps=["claude", "opencode", "openclaw", "open_webui"],
    ),
    ProviderPresetRecord(
        key="modelscope",
        name="ModelScope",
        provider_type="modelscope",
        default_base_url="https://api-inference.modelscope.cn/v1",
        api_format="openai",
        suggested_apps=["claude", "opencode", "openclaw", "open_webui"],
    ),
    ProviderPresetRecord(
        key="kat_coder",
        name="KAT-Coder",
        provider_type="kat_coder",
        default_base_url="https://api.katcoder.com/v1",
        api_format="openai",
        suggested_apps=["claude", "opencode", "openclaw", "codex", "open_webui"],
    ),
    ProviderPresetRecord(
        key="longcat",
        name="Longcat",
        provider_type="longcat",
        default_base_url="https://api.longcat.chat/v1",
        api_format="openai",
        suggested_apps=["claude", "opencode", "openclaw", "open_webui"],
    ),
    ProviderPresetRecord(
        key="minimax",
        name="MiniMax",
        provider_type="minimax",
        default_base_url="https://api.minimax.chat/v1",
        api_format="openai",
        suggested_apps=["claude", "opencode", "openclaw", "open_webui"],
    ),
    ProviderPresetRecord(
        key="minimax_en",
        name="MiniMax (EN)",
        provider_type="minimax",
        default_base_url="https://api.minimax.chat/v1",
        api_format="openai",
        suggested_apps=["claude", "opencode", "openclaw", "open_webui"],
    ),
    ProviderPresetRecord(
        key="doubao_seed",
        name="DouBao Seed",
        provider_type="doubao",
        default_base_url="https://ark.cn-beijing.volces.com/api/v3",
        api_format="openai",
        suggested_apps=["claude", "opencode", "openclaw", "open_webui"],
    ),
    ProviderPresetRecord(
        key="bailing",
        name="BaiLing",
        provider_type="bailing",
        default_base_url="https://api.bailing.chat/v1",
        api_format="openai",
        suggested_apps=["claude", "opencode", "openclaw", "open_webui"],
    ),
    ProviderPresetRecord(
        key="siliconflow",
        name="SiliconFlow",
        provider_type="siliconflow",
        default_base_url="https://api.siliconflow.cn/v1",
        api_format="openai",
        suggested_apps=["claude", "opencode", "openclaw", "open_webui"],
    ),
    ProviderPresetRecord(
        key="siliconflow_en",
        name="SiliconFlow (EN)",
        provider_type="siliconflow",
        default_base_url="https://api.siliconflow.cn/v1",
        api_format="openai",
        suggested_apps=["claude", "opencode", "openclaw", "open_webui"],
    ),
    ProviderPresetRecord(
        key="nvidia",
        name="Nvidia",
        provider_type="nvidia",
        default_base_url="https://integrate.api.nvidia.com/v1",
        api_format="openai",
        suggested_apps=["claude", "opencode", "openclaw", "open_webui"],
    ),
    ProviderPresetRecord(
        key="xiaomi_mimo",
        name="Xiaomi MiMo",
        provider_type="xiaomi",
        default_base_url="https://api.mimo.mi.com/v1",
        api_format="openai",
        suggested_apps=["claude", "opencode", "openclaw", "open_webui"],
    ),
    ProviderPresetRecord(
        key="aws_bedrock",
        name="AWS Bedrock",
        provider_type="bedrock",
        default_base_url="https://bedrock-runtime.{region}.amazonaws.com",
        api_format="openai",
        suggested_apps=["openclaw", "opencode", "open_webui"],
    ),
    ProviderPresetRecord(
        key="aihubmix",
        name="AiHubMix",
        provider_type="aihubmix",
        default_base_url="https://api.aihubmix.com/v1",
        api_format="openai",
        suggested_apps=["claude", "codex", "gemini", "opencode", "openclaw", "open_webui"],
    ),
    ProviderPresetRecord(
        key="dmxapi",
        name="DMXAPI",
        provider_type="dmxapi",
        default_base_url="https://www.dmxapi.cn/v1",
        api_format="openai",
        suggested_apps=["claude", "codex", "opencode", "openclaw", "open_webui"],
    ),
    ProviderPresetRecord(
        key="packycode",
        name="PackyCode",
        provider_type="packycode",
        default_base_url="https://api.packycode.com/v1",
        api_format="openai",
        suggested_apps=["claude", "codex", "gemini", "opencode", "openclaw", "open_webui"],
    ),
    ProviderPresetRecord(
        key="cubence",
        name="Cubence",
        provider_type="cubence",
        default_base_url="https://api.cubence.com/v1",
        api_format="openai",
        suggested_apps=["claude", "codex", "gemini", "opencode", "openclaw", "open_webui"],
    ),
    ProviderPresetRecord(
        key="aigocode",
        name="AIGoCode",
        provider_type="aigocode",
        default_base_url="https://api.aigocode.com/v1",
        api_format="openai",
        suggested_apps=["claude", "codex", "gemini", "opencode", "openclaw", "open_webui"],
    ),
    ProviderPresetRecord(
        key="rightcode",
        name="RightCode",
        provider_type="rightcode",
        default_base_url="https://api.rightcode.cn/v1",
        api_format="openai",
        suggested_apps=["claude", "codex", "opencode", "openclaw", "open_webui"],
    ),
    ProviderPresetRecord(
        key="aicodemirror",
        name="AICodeMirror",
        provider_type="aicodemirror",
        default_base_url="https://api.aicodemirror.com/v1",
        api_format="openai",
        suggested_apps=["claude", "codex", "gemini", "opencode", "openclaw", "open_webui"],
    ),
    ProviderPresetRecord(
        key="aicoding",
        name="AICoding",
        provider_type="aicoding",
        default_base_url="https://api.aicoding.cc/v1",
        api_format="openai",
        suggested_apps=["openclaw", "opencode", "open_webui"],
    ),
    ProviderPresetRecord(
        key="crazyrouter",
        name="CrazyRouter",
        provider_type="crazyrouter",
        default_base_url="https://api.crazyrouter.ai/v1",
        api_format="openai",
        suggested_apps=["openclaw", "opencode", "open_webui"],
    ),
    ProviderPresetRecord(
        key="sssaicode",
        name="SSSAiCode",
        provider_type="sssaicode",
        default_base_url="https://api.sssaicode.com/v1",
        api_format="openai",
        suggested_apps=["openclaw", "opencode", "open_webui"],
    ),
    ProviderPresetRecord(
        key="openrouter",
        name="OpenRouter",
        provider_type="openrouter",
        default_base_url="https://openrouter.ai/api",
        api_format="openai",
        suggested_apps=["claude", "codex", "gemini", "opencode", "openclaw", "open_webui"],
    ),
    ProviderPresetRecord(
        key="openai_compatible",
        name="OpenAI Compatible",
        provider_type="openai_compatible",
        default_base_url="https://api.example.com",
        api_format="openai",
        suggested_apps=["claude", "codex", "gemini", "opencode", "openclaw", "open_webui"],
    ),
    ProviderPresetRecord(
        key="oh_my_opencode",
        name="Oh My OpenCode",
        provider_type="opencode_proxy",
        default_base_url="https://api.ohmyopencode.com/v1",
        api_format="openai",
        suggested_apps=["opencode", "open_webui"],
    ),
    # -----------------------------------------------------------------------
    # 国际主流供应商
    # -----------------------------------------------------------------------
    ProviderPresetRecord(
        key="groq",
        name="Groq",
        provider_type="groq",
        default_base_url="https://api.groq.com/openai/v1",
        api_format="openai",
        suggested_apps=["opencode", "openclaw", "open_webui"],
    ),
    ProviderPresetRecord(
        key="mistral",
        name="Mistral AI",
        provider_type="mistral",
        default_base_url="https://api.mistral.ai/v1",
        api_format="openai",
        suggested_apps=["opencode", "openclaw", "open_webui"],
    ),
    ProviderPresetRecord(
        key="together_ai",
        name="Together AI",
        provider_type="together_ai",
        default_base_url="https://api.together.xyz/v1",
        api_format="openai",
        suggested_apps=["opencode", "openclaw", "open_webui"],
    ),
    ProviderPresetRecord(
        key="perplexity",
        name="Perplexity AI",
        provider_type="perplexity",
        default_base_url="https://api.perplexity.ai",
        api_format="openai",
        suggested_apps=["opencode", "open_webui"],
    ),
    ProviderPresetRecord(
        key="cohere",
        name="Cohere",
        provider_type="cohere",
        default_base_url="https://api.cohere.ai/v1",
        api_format="openai",
        suggested_apps=["opencode", "open_webui"],
    ),
    ProviderPresetRecord(
        key="fireworks",
        name="Fireworks AI",
        provider_type="fireworks_ai",
        default_base_url="https://api.fireworks.ai/inference/v1",
        api_format="openai",
        suggested_apps=["opencode", "openclaw", "open_webui"],
    ),
    ProviderPresetRecord(
        key="replicate",
        name="Replicate",
        provider_type="replicate",
        default_base_url="https://api.replicate.com/v1",
        api_format="openai",
        suggested_apps=["open_webui"],
    ),
    ProviderPresetRecord(
        key="anyscale",
        name="Anyscale",
        provider_type="anyscale",
        default_base_url="https://api.endpoints.anyscale.com/v1",
        api_format="openai",
        suggested_apps=["opencode", "open_webui"],
    ),
    # -----------------------------------------------------------------------
    # 国内主流供应商（CC Switch 未收录但常用）
    # -----------------------------------------------------------------------
    ProviderPresetRecord(
        key="baidu_ernie",
        name="百度文心 (ERNIE)",
        provider_type="baidu_ernie",
        default_base_url="https://qianfan.baidubce.com/v2",
        api_format="openai",
        suggested_apps=["opencode", "openclaw", "open_webui"],
    ),
    ProviderPresetRecord(
        key="iflytek_spark",
        name="讯飞星火 (Spark)",
        provider_type="iflytek",
        default_base_url="https://spark-api-open.xf-yun.com/v1",
        api_format="openai",
        suggested_apps=["opencode", "openclaw", "open_webui"],
    ),
    ProviderPresetRecord(
        key="baichuan",
        name="百川 (Baichuan)",
        provider_type="baichuan",
        default_base_url="https://api.baichuan-ai.com/v1",
        api_format="openai",
        suggested_apps=["opencode", "openclaw", "open_webui"],
    ),
    ProviderPresetRecord(
        key="tencent_hunyuan",
        name="腾讯混元 (Hunyuan)",
        provider_type="hunyuan",
        default_base_url="https://api.hunyuan.cloud.tencent.com/v1",
        api_format="openai",
        suggested_apps=["opencode", "openclaw", "open_webui"],
    ),
    ProviderPresetRecord(
        key="lingyiwanwu",
        name="零一万物 (Yi-Large)",
        provider_type="lingyiwanwu",
        default_base_url="https://api.lingyiwanwu.com/v1",
        api_format="openai",
        suggested_apps=["opencode", "openclaw", "open_webui"],
    ),
    ProviderPresetRecord(
        key="custom_openai_compatible",
        name="Custom OpenAI Compatible",
        provider_type="custom",
        default_base_url="https://api.example.com",
        api_format="openai",
        suggested_apps=["claude", "codex", "gemini", "opencode", "openclaw", "open_webui"],
    ),
]
